"""update contact fields and nullability

Revision ID: 9160583eff26
Revises: 5f109089b354
Create Date: 2026-06-09 23:59:57.414599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9160583eff26'
down_revision: Union[str, Sequence[str], None] = '5f109089b354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('description', sa.String(length=250), nullable=True))
    op.alter_column('contacts', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('contacts', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('contacts', 'birthday',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_unique_constraint(None, 'contacts', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='unique')
    op.alter_column('contacts', 'birthday',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('contacts', 'phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('contacts', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('contacts', 'description')
    # ### end Alembic commands ###
